#!/usr/bin/env sh

TO_DIR="$HOME/.to"

usage(){
 cat <<EOF
usage:
 to -n <label> [<program>]  # new session
 to <label>                 # existing session
 to -l                      # list sessions
EOF
 exit 1;
}

n(){
 m=`umask`; umask 0077; mkdir -p "$TO_DIR"; umask "$m"
 TO="$1" exec dtach -c "$TO_DIR/$1" "$2"
}

l() {
 exec find "$TO_DIR" -type s -exec basename {} \;
}

e() {
 exec dtach -a "$TO_DIR/$1"
}

if [ x"$1" = x"-n" ]; then
 [ $# -eq 2 ] && n "$2" "$SHELL"
 [ $# -eq 3 ] && n "$2" "$3"
 usage
elif [ x"$1" = x"-l" ]; then
 [ $# -eq 1 ] && l
 usage
else
 [ $# -eq 1 ] && e "$1"
 usage
fi
