#!/usr/bin/env sh

TO_DIR="$HOME/.to"

usage(){
 cat <<EOF
usage:
 to -n <label> [<program>]  # new session
 to <label>                 # existing session
 to -l                      # list sessions
EOF
 exit 1;
}

n(){
 m=`umask`; umask 0077; mkdir -p "$TO_DIR"; umask "$m"
 TO="$1"
 shift
 TO="$TO" exec dtach -c "$TO_DIR/$TO" "$@"
}

l() {
 exec find "$TO_DIR" -type s -exec basename {} \;
}

e() {
 exec dtach -a "$TO_DIR/$1"
}

if [ x"$1" = x"-n" ]; then
 if [ $# -gt 1 ]; then
  shift
  NAME="$1"
  shift
  [ $# -eq 0 ] && n "$NAME" "$SHELL"
  [ $# -gt 0 ] && n "$NAME" "$@"
 else
  usage
 fi
elif [ x"$1" = x"-l" ]; then
 [ $# -eq 1 ] && l
 usage
else
 [ $# -eq 1 ] && e "$1"
 usage
fi
